name: Deploy to shinyapps.io

on:
  push:
    branches: [main]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run:
          install.packages(c("remotes", "rsconnect", "shiny", "learnr", "ggplot2"))
          
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run:
          rsconnect::setAccountInfo(name = Sys.getenv("SHINYAPPS_ACCOUNT"),
                                    token = Sys.getenv("SHINYAPPS_TOKEN"),
                                    secret = Sys.getenv("SHINYAPPS_SECRET"))
                                    
          shiny::runApp()
        shell: Rscript {0}
